#!/bin/bash
# Kirk Steuber, 2022-11-26

# This is a thin wrapper around the installer python package. It exists to make sure that
# python exists and to make it slightly cleaner to invoke the installer properly.

python_bin="$(which python3 2>/dev/null)"

if [[ -z "$python_bin" ]]; then
  echo "Cannot find python3! Install it from https://www.python.org/downloads/" >&2
  exit
fi

cd "$(dirname "$0")"

# When using the `-m` switch, the current directory will be added to the start of sys.path. So
# this will safely load the version in the current directory, even if a conflicting package exists.
"$python_bin" -m installer "$@"
