#!/bin/bash

# This is a thin wrapper around the installer python package. It exists to make sure that
# python exists and to make it slightly cleaner to invoke the installer properly.

python_bin="$(which python3 2>/dev/null)"

if [[ -z "$python_bin" ]]; then
  python_bin="$(which python 2>/dev/null)"
fi

if [[ -z "$python_bin" ]]; then
  echo "Cannot find python3($python_bin)! Install it from https://www.python.org/downloads/" >&2
  if [[ "$OSTYPE" == "msys" ]]; then
    echo
    echo "Also recreate the shortcut to the terminal to point to:" >&2
    echo "C:\msys64\msys2_shell.cmd -full-path" >&2
  fi
  exit
fi

python_version="$("$python_bin" --version)"
if [[ "$python_version" == "Python 3."* ]]; then
  echo "Found python3 at \"$python_bin\""
else
  echo "Unable to find Python 3. Could only find $python_version"
  exit
fi

cd "$(dirname "$0")"

# When using the `-m` switch, the current directory will be added to the start of sys.path. So
# this will safely load the version in the current directory, even if a conflicting package exists.
"$python_bin" -m installer "$@"
